[package]
name = "scooper-v2"
description = "Server for Sundae Scooper"
version = "0.6.0"
edition = "2024"
repository = "https://github.com/SundaeSwap-finance/scooper-v2"
license-file = "LICENSE"
publish = false

[dependencies]
acropolis_common = { version = "0.3.0", git = "https://github.com/input-output-hk/acropolis.git", rev = "2c0a32c" }
acropolis_module_block_unpacker = { version = "0.2.0", git = "https://github.com/input-output-hk/acropolis.git", rev = "2c0a32c" }
acropolis_module_custom_indexer = { version = "0.1.0", git = "https://github.com/input-output-hk/acropolis.git", rev = "2c0a32c" }
acropolis_module_genesis_bootstrapper = { version = "0.1.0", git = "https://github.com/input-output-hk/acropolis.git", rev = "2c0a32c" }
acropolis_module_mithril_snapshot_fetcher = { version = "0.1.0", git = "https://github.com/input-output-hk/acropolis.git", rev = "2c0a32c" }
acropolis_module_peer_network_interface = { version = "0.2.0", git = "https://github.com/input-output-hk/acropolis.git", rev = "2c0a32c" }
anyhow = "1"
async-trait = "0.1"
caryatid_sdk = { version = "0.14.1", git = "https://github.com/input-output-hk/caryatid.git", rev = "538c3f8" }
caryatid_process = { version = "0.14.3", git = "https://github.com/input-output-hk/caryatid.git", rev = "538c3f8" }
chrono = "0.4"
clap = { version = "4.5.41", features = ["derive"] }
config = "0.15.11"
hex = { version = "0.4", features = ["serde"] }
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
minicbor = { version = "0.25.0", features = ["alloc", "derive"] }
num-bigint = "0.4.6"
num-traits = "0.2.19"
pallas-addresses = "0.34"
pallas-codec = "0.34"
pallas-crypto = "0.34"
pallas-primitives = "0.34"
pallas-network = "0.34"
pallas-traverse = "0.34"
reqwest = { version = "0.13", features = ["rustls", "json"], default-features = false }
rustls-pemfile = "2"
url = "2"
plutus-parser = { version = "0.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "tls-rustls"] }
thiserror = "2"
tokio = { version = "1.46.1", features = ["full"] }
tokio-rustls = "0.26"
tokio-util = "0.7"
uplc-turbo = { version = "0.1.0", git = "https://github.com/pragma-org/uplc.git", rev = "6152616" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "std",
  "json",
] }

[dev-dependencies]
proptest = "1"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[package.metadata.dist]
dist = true
