# Acropolis

[acropolis.global.startup]
topic = "cardano.sequence.start"
sync-mode = "upstream"

[acropolis.module.genesis-bootstrapper]

[acropolis.module.peer-network-interface]
block-topic = "cardano.block.proposed"
sync-point = "dynamic"

[acropolis.module.mithril-snapshot-fetcher]
block-publish-topic = "cardano.block.proposed"
# Download max age in hours. E.g. 8 means 8 hours (if there isn't any snapshot within this time range download from Mithril)
download-max-age = "never"

[acropolis.module.block-unpacker]

[acropolis.module.custom-indexer]

[acropolis.message-bus.internal]
class = "in-memory"
workers = 50
dispatch-queue-size = 1000
worker-queue-size = 100
bulk-block-capacity = 50
bulk-resume-capacity = 75

# Message routing
[[acropolis.message-router.route]]
pattern = "#"
bus = "internal"
